name: 掘金签到自动执行任务
on:
  schedule:
    # 分 时 日 月 星期
    - cron: '0 23 * * *'   # UTC 23:00 → 北京 07:00（第二天）
  workflow_dispatch:       # 保留手动触发按钮，方便调试
jobs:
  JueJinCheckIn:
    runs-on: ubuntu-latest
    env:
      COOKIE: ${{ secrets.COOKIE }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 检查仓库文件
        run: ls -al

      - name: 设置node环境
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: 检查node环境
        run: node --version

      - name: 卸载系统Chrome
        run: |
          sudo apt-get remove -y google-chrome-stable
          sudo apt-get autoremove -y

      - name: 设置系统Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 141.0.7390.78

      - name: 安装依赖
        run: npm install

      - name: 检查ChromeDriver依赖
        run: /home/runner/work/auto-script-executer-collection/auto-script-executer-collection/node_modules/chromedriver/lib/chromedriver/chromedriver --version

      - name: 检查系统Chrome
        run: chrome --version

      - name: 执行脚本
        run: node ./src/juejin_check_in.js